# Autogenerated wrapper script for tensorprimitives_tapp_jll for i686-linux-gnu
export libtensorprimitives_tapp, tapp_h

JLLWrappers.@generate_wrapper_header("tensorprimitives_tapp")
JLLWrappers.@declare_library_product(libtensorprimitives_tapp, "libtensorprimitives_tapp.so")
JLLWrappers.@declare_file_product(tapp_h)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtensorprimitives_tapp,
        "lib/libtensorprimitives_tapp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        tapp_h,
        "include/tapp.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
