# Autogenerated wrapper script for tensorprimitives_tapp_jll for x86_64-w64-mingw32
export libtensorprimitives_tapp, tapp_h

JLLWrappers.@generate_wrapper_header("tensorprimitives_tapp")
JLLWrappers.@declare_library_product(libtensorprimitives_tapp, "tensorprimitives_tapp.dll")
JLLWrappers.@declare_file_product(tapp_h)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtensorprimitives_tapp,
        "bin\\tensorprimitives_tapp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        tapp_h,
        "include\\tapp.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
